### PR TITLE
Fixes https://github.com/crisu83/yiistrap/issues/289

### PR DESCRIPTION
**Pull request by marcovtwout**

### CODE REVIEW

**Comment by marcovtwout** [comment]
Please merge it :)

**Comment by crisu83** [comment]
Why don't you use the TbArray methods? It would be nice to have a clean implementation of this fix.

**Comment by marcovtwout** [comment]
Refactored as requested.

**Comment by crisu83** [comment]
I would prefer skipping the option of giving ```empty``` as an array if possible to make the code more readable like so:

```php
$empty = TbArray::popValue('empty', $htmlOptions);
if (isset($empty)) {
  $data = TbArray::merge(['' => $empty], $data);
}
```

**Comment by marcovtwout** [comment]
I would prefer to stick as close to original Yii behavior as possible. If we do this, we need less yiistrap-specific documentation, make the switch to yiistrap easier, and call for less unexpected behaviors. That's why I did earlier additions like https://github.com/crisu83/yiistrap/pull/228.

I think all this outweights the slighty more readable code, and I think this principle could apply in general for any yiistrap addition or modification. What do you think?

**Comment by crisu83** [comment]
I updated the code above, does that look OK to you?

**Comment by marcovtwout** [comment]
Looks good, added to PR.

**Pull request merged**
