### PR TITLE
Fix #271 uncheck value option

### LINKED ISSUE #271: ::activeRadioButtonList() 'uncheckValue' doesn't work
There was an issue https://github.com/crisu83/yiistrap/issues/167
But new solution doesn't work either

```php
$uncheckValue = isset($htmlOptions['uncheckValue']) ? TbArray::popValue('uncheckValue', $htmlOptions) : '';
$hidden = isset($uncheckValue) ? parent::hiddenField($name, $uncheckValue, $hiddenOptions) : '';
```
`$hidden` will never be `''` as `isset($uncheckValue)` will always return `true`.

Possible solutions would be to use `null` instead of `''`:
```php
$uncheckValue = isset($htmlOptions['uncheckValue']) ? TbArray::popValue('uncheckValue', $htmlOptions) : null;
$hidden = isset($uncheckValue) ? parent::hiddenField($name, $uncheckValue, $hiddenOptions) : '';
```

### PR DESCRIPTION
**Pull request by velosipedist**
Fixes #271

### CODE REVIEW

**Comment by velosipedist** [comment]
The tests should fail now, waiting for output...

**Comment by velosipedist** [comment]
you're welcome to check

**Comment by crisu83** [comment]
Please use ```$uncheckValue !== null``` instead of ```!is_null($uncheckValue)```. When all the builds pass I can merge this.

**Comment by velosipedist** [comment]
Done

**Comment by crisu83** [comment]
Looks good, thanks.

**Pull request merged**
